# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Copie dans le dossier du projet
        run: cp -rf /home/github/actions-runner/_work/bloc-notes-bot/bloc-notes-bot/. /home/github/bloc-notes-bot

      - name: Installation des dépendance
        run: |
          cp -rf /home/github/actions-runner/_work/bloc-notes-bot/bloc-notes-bot/. /home/github/bloc-notes-bot
          cd /home/github/bloc-notes-bot && pwd && npm i
